"""second

Revision ID: 0a454d3edcba
Revises: c3d132cd9060
Create Date: 2021-07-10 23:57:49.090799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a454d3edcba'
down_revision = 'c3d132cd9060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
