# Generated by Django 2.2.5 on 2019-09-30 01:16
import uuid

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created', models.DateTimeField(default=timezone.now)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
