# Generated by Django 2.2.5 on 2019-10-02 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDeleted',
            fields=[
                (
                    'created',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'goal',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='goals.Goal',
                    ),
                ),
            ],
        ),
    ]
