# Generated by Django 2.2.5 on 2019-10-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goaldeleted_20191002_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('not_started', 'Task has not been started'), ('in_progress', 'Task has been started and is in progress'), ('completed', 'Task has been completed')], default='not_started', max_length=200),
        ),
    ]
