# Generated by Django 2.2.5 on 2019-10-02 04:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'created',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'device_id',
                    models.CharField(max_length=256, unique=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
