# Generated by Django 2.2.5 on 2019-10-05 01:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'created',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
