# Generated by Django 2.2.5 on 2019-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_id',
            field=models.UUIDField(default=123),
            preserve_default=False,
        ),
    ]
