# Generated by Django 2.2.5 on 2019-10-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('not_started', 'Task has not been started')],
                default='not_started',
                max_length=200,
            ),
        ),
    ]
