# Generated by Django 2.2.5 on 2019-10-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
