"""zz

Revision ID: 3312442dac5d
Revises: f0b8c1666249
Create Date: 2021-07-11 00:34:49.904030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3312442dac5d'
down_revision = 'f0b8c1666249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
