"""third

Revision ID: f0b8c1666249
Revises: 0a454d3edcba
Create Date: 2021-07-10 23:58:44.795081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b8c1666249'
down_revision = '0a454d3edcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
